name: "<npm publish template>"
on:
  workflow_call:
    inputs:
      auth-token:
        required: true
        type: string

      registry-url:
        default: https://registry.npmjs.org
        required: false
        type: string

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Artifact download
        uses: actions/download-artifact@v3
        with:
          name: byloth-vue-scroll-animator-core

      - name: Node.js 18 (LTS) setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: ${{ inputs.registry-url }}

      - name: Package release
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ inputs.auth_token }}
