name: GPR release
on:
  release:
    types: [published]

jobs:
  artifact-build:
    name: Artifact
    uses: ./.github/workflows/build-core-template.yml

  gpr-release:
    name: GPR
    needs: artifact-build
    uses: ./.github/workflows/release-template.yml
    with:
      auth-token: ${{ secrets.GITHUB_TOKEN }}
      registry-url: https://npm.pkg.github.com/
