name: "<template:publish:core>"
on:
  workflow_call:
    inputs:
      registry-url:
        default: https://registry.npmjs.org
        required: false
        type: string

    secrets:
      AUTH_TOKEN:
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Artifact download
        uses: actions/download-artifact@v3
        with:
          name: byloth-vue-scroll-animator-core

      - name: Node.js 18 (LTS) setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: ${{ inputs.registry-url }}

      - name: Package publish
        run: npm publish --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
